function y = preprocess(x,Fs)
%  预处理输入 x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 17-Apr-2025 14:37:33

y = highpass(x,1,Fs,'Steepness',0.85,'StopbandAttenuation',60);
y = lowpass(y,40,Fs,'Steepness',0.85,'StopbandAttenuation',60);
y = bandstop(y,[98 102],Fs,'Steepness',0.85,'StopbandAttenuation',60);
y = bandstop(y,[48 52],Fs,'Steepness',0.85,'StopbandAttenuation',60);
